routes/web.php
<?php

use App\Http\Controllers\AboutUsController;
use App\Http\Controllers\AreaController;
use App\Http\Controllers\Backend\AdsController;
use App\Http\Controllers\Backend\LanguageController;
use App\Http\Controllers\Backend\RoleController;
use App\Http\Controllers\Backend\SectionController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FrontendController;

use App\Http\Controllers\SegmentController;
use App\Http\Controllers\SubscribeController;

use App\Http\Controllers\UserController;
use App\Http\Controllers\WebsiteSettingController;
use App\Models\Language;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\SubCategoryController;
use \App\Http\Controllers\Backend\PostController;
use \App\Http\Controllers\Backend\SettingController;
use \App\Http\Controllers\Backend\GalleryController;
use \App\Http\Controllers\Frontend\ExtraController;
use \Mcamara\LaravelLocalization\Facades\LaravelLocalization;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth:sanctum','verified'])->group(function ()
{
    Route::middleware(['admin'])->group(function () {
        Route::get('/dashboard',[AdminController::class, 'Dashboard'])->name('dashboard');
        Route::view('/profile/edit','profile.edit')->name('profile');
        Route::view('/profile/password','profile.password')->name('password');
    });
});

//Logout
Route::get('/admin/logout', [AdminController::class, 'Logout'])->name('admin.logout');
//Route::get('/language/change/{lang}',[AdminController::class,'GetLang'])->name('admin.lang');


//Admin Areas
Route::get('/add/area', [AreaController::class, 'AddArea'])->name('add.area');
Route::post('/store/area', [AreaController::class, 'StoreArea'])->name('store.area');
Route::get('/areas', [AreaController::class, 'Index'])->name('index.area');
Route::get('/edit/area/{id}', [AreaController::class, 'EditArea'])->name('edit.area');
Route::post('/update/area/{id}', [AreaController::class, 'UpdateArea'])->name('update.area');
Route::get('/delete/area/{id}', [AreaController::class, 'DeleteArea'])->name('delete.area');


//About US
Route::get('/edit/aboutUs/{id}', [AboutUsController::class, 'EditAboutUs'])->name('edit.aboutUs');
Route::post('/update/aboutUs/{id}', [AboutUsController::class, 'UpdateAboutUs'])->name('update.aboutUs');

//Admin Category
Route::get('/categories', [CategoryController::class, 'Index'])->name('categories');
Route::get('/add/category', [CategoryController::class, 'AddCategory'])->name('add.category');
Route::get('/edit/category/{id}', [CategoryController::class, 'EditCategory'])->name('edit.category');
Route::get('/delete/category/{id}', [CategoryController::class, 'DeleteCategory'])->name('delete.category');
Route::post('/store/category', [CategoryController::class, 'StoreCategory'])->name('store.category');
Route::post('/update/category/{id}', [CategoryController::class, 'UpdateCategory'])->name('update.category');

//Category Json
Route::get('/get/subcategory/{category_id}', [PostController::class, 'GetSubCategory']);

//Sections
Route::get('/slider', [SectionController::class, 'Slider'])->name('section.slider');
Route::get('create/slider', [SectionController::class, 'SliderCreate'])->name('section.slider.add');
Route::post('/slider/save', [SectionController::class, 'SliderSave'])->name('section.slider.save');

Route::middleware([\App\Http\Middleware\SectionMiddleware::class])->group(function () {

    Route::get('/most-important-news',[SectionController::class, 'MostImportantNews'])->name('section.mostImportantNews');
    Route::post('/most-important/save', [SectionController::class, 'MostImportantNewsSave'])->name('section.mostImportantNews.save');
    Route::get('/audio-news',[SectionController::class, 'AudioNews'])->name('section.audioNews');
    Route::post('/audio-news/save', [SectionController::class, 'AudioNewsSave'])->name('section.audioNews.save');
    Route::post('/audio-news/save', [SectionController::class, 'AudioNewsSave'])->name('section.audioNews.save');
    Route::get('/category-segments',[SegmentController::class, 'Index'])->name('index.category_segment');
    Route::get('/add-category-segments',[SegmentController::class, 'AddSegment'])->name('add.category_segment');
    Route::get('/edit-category-segments/{id}',[SegmentController::class, 'EditSegment'])->name('edit.category_segment');
    Route::post('/segment/save', [SegmentController::class, 'StoreSegment'])->name('store.category_segment');
    Route::post('/segment/update', [SegmentController::class, 'UpdateSegment'])->name('update.segment');
    Route::get('/delete/segment/{id}', [SegmentController::class, 'DeleteSegment'])->name('delete.segment');

});

//Admin Subcategory
Route::get('/subcategories', [SubCategoryController::class, 'Index'])->name('subcategories');
Route::get('/add/subcategory', [SubCategoryController::class, 'AddSubCategory'])->name('add.subcategory');
Route::get('/edit/subcategory/{id}', [SubCategoryController::class, 'EditSubCategory'])->name('edit.subcategory');
Route::post('/store/subcategory', [SubCategoryController::class, 'StoreSubCategory'])->name('store.subcategory');
Route::post('/update/subcategory/{id}', [SubCategoryController::class, 'UpdateSubCategory'])->name('update.subcategory');
Route::get('/delete/subcategory/{id}', [SubCategoryController::class, 'DeleteSubCategory'])->name('delete.subcategory');
//Route::get('/delete/subcategory/{id}', [SubCategoryController::class, 'DeleteSubCategory'])->name('delete.subcategory');


Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
//Admin Post
    Route::get('/all/lang', [LanguageController::class, 'Index'])->name('language.all');
    Route::get('/create/lang', [LanguageController::class, 'Create'])->name('language.create');
    Route::post('/store/lang', [LanguageController::class, 'Store'])->name('language.store');
    Route::get('/edit/lang/{id}', [LanguageController::class, 'Edit'])->name('language.edit');
    Route::get('pages/config/edittranslation{edit?}', [LanguageController::class, 'EditTranslation'])->name('translation.edit');
    Route::post('/save/translation', [LanguageController::class, 'SaveTranslation'])->name('translation.save');
    Route::get('/language/delete/{id}', [LanguageController::class, 'Delete'])->name('language.delete');
    Route::post('/language/update/{id}', [LanguageController::class, 'Update'])->name('language.update');

    Route::get('/create/post', [PostController::class, 'Create'])->name('create.post');
    Route::post('/store/post', [PostController::class, 'StorePost'])->name('store.post');
    Route::get('/all_post', [PostController::class, 'Index'])->name('all.post');
    Route::get('/edit_post/{id}', [PostController::class, 'EditPost'])->name('edit.post');
    Route::get('/delete_post/{id}', [PostController::class, 'DeletePost'])->name('delete.post');
    Route::post('/update/post/{id}', [PostController::class, 'UpdatePost'])->name('update.post');
});




//About us
Route::get('/website/aboutUs', [AboutUsController::class, 'Index'])->name('AboutUs');

//settings
Route::get('/social/setting', [SettingController::class, 'SocialSetting'])->name('social.setting');
Route::post('/social/update/{id?}', [SettingController::class, 'SocialUpdate'])->name('update.social');
Route::get('/seo/setting', [SettingController::class, 'SeoSetting'])->name('seo.setting');
Route::post('/seo/update/{id}', [SettingController::class, 'SeoUpdate'])->name('update.seo');
Route::get('/live_tv/setting', [SettingController::class, 'LiveTvSetting'])->name('live_tv.setting');
Route::post('/live_tv/update/{id}', [SettingController::class, 'LiveTvUpdate'])->name('update.live_tv');
//live_tv active inactive
Route::get('/live_tv/active/{id}', [SettingController::class, 'Active_LiveTV'])->name('active.live_tv');
Route::get('/live_tv/inactive/{id}', [SettingController::class, 'Inactive_LiveTV'])->name('inactive.live_tv');
Route::get('/notice/setting', [SettingController::class, 'NoticeSetting'])->name('notice.setting');
Route::post('/notice/update/{id}', [SettingController::class, 'NoticeUpdate'])->name('update.notice');
Route::get('/notice/active/{id}', [SettingController::class, 'ActiveNoticeSetting'])->name('active.notice');
Route::get('/notice/inactive/{id}', [SettingController::class, 'InActiveNoticeSetting'])->name('inactive.notice');

//Website
Route::get('/website/setting', [SettingController::class, 'WebsiteSetting'])->name('all.website');
Route::get('/logo/setting', [SettingController::class, 'Logo'])->name('settings');
Route::get('/logo/edit/{id}', [SettingController::class, 'LogoEdit'])->name('settings.edit.logo');
Route::post('/logo/update/{id}', [SettingController::class, 'LogoUpdate'])->name('settings.update.logo');
Route::get('/add/website', [SettingController::class, 'AddWebsiteSetting'])->name('add.website');
Route::post('/store/website', [SettingController::class, 'StoreWebsite'])->name('store.website');
Route::get('/edit_website/{id}', [SettingController::class, 'EditWebsite'])->name('edit.website');
Route::post('/update/website/{id}', [SettingController::class, 'UpdateWebsite'])->name('update.website');
Route::get('/delete_website/{id}', [SettingController::class, 'DeleteWebsite'])->name('delete.website');

//Gallery
Route::get('/photo/gallery', [GalleryController::class, 'PhotoGallery'])->name('photo.gallery');

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;
    public $guarded=[];
    public function users()
    {
        return $this->belongsToMany(User::class);
    }
}

app/Http/Controllers/Backend/AdsController.php
<?php

namespace App\Http\Controllers\Backend;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;

class AdsController extends Controller
{
    public function AdList()
    {
        $ads=DB::table('ads')->orderBy('id','desc')->get();
        return view('backend.ads.index',compact('ads'));
    }
    public function Create()
    {
        return view('backend.ads.create');
    }

    public function Store(Request $request)
    {
        $data = array();
        $data['link']=$request->link;
        $data['type']=$request->type;
        $image=$request->ads;
        $validated = $request->validate([
            'link' => 'required',
            'ads' => 'required',
        ]);

        if ($request->type == 0) {
            if ($image) {
                $image_uni = uniqid() . '.' . $image->getClientOriginalExtension();
                Image::make($image)->resize(1170, 282)->save('storage/ads/'.$image_uni);
                $data['ads'] = 'storage/ads/' . $image_uni;
                DB::table('ads')->insert($data);
            }
        }
        else
        {
            if ($image) {

                $image_uni = uniqid() . '.' . $image->getClientOriginalExtension();
                Image::make($image)->resize(500, 300)->save('storage/ads/'.$image_uni);
                $data['ads'] = 'storage/ads/' . $image_uni;
                DB::table('ads')->insert($data);
            }
        }
        $notification = array(
            'message' => 'Ad Inserted successfully',
            'alert-type' => 'success'
        );
        return redirect()->route('ad.list');

    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Middleware\RedirectIfAuthenticated;
use App\Models\Category;
use App\Models\CategoryTranslation;
use App\Models\Language;
use Brian2694\Toastr\Toastr;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CategoryController extends Controller
{
    public function Index()
    {
        $defaultLanguage = Language::getDefaultLanguage();
        $defaultLanguageId = $defaultLanguage->id;
        $category = DB::table('categories')->orderBy('categories.id', 'desc')
        ->Join('category_translations', 'categories.id', 'category_translations.category_id')
        ->where('category_translations.language_id', $defaultLanguageId)
            ->select('category_translations.category_name','categories.id')
        ->paginate(3);
        return view('backend.category.index', compact('category'));
    }

    public function AddCategory()
    {
        return view('backend.category.create');
    }

    public function StoreCategory(Request $request)
    {
        $validate_array = ['category_name' => 'required|unique:category_translations|max:255'];
        $status = $request->status ? 1 : 0;
        $notification = array(
            'message' => 'Category Inserted successfully',
            'alert-type' => 'success'
        );
        $category = Category::create(['status'=>$status]);
        foreach (Language::all() as $key => $value) {
            $validate_array["category_name.$value->id"] = 'required';
            $translated[$key] = [
                'category_name' => $request->input("category_name.$value->id"),
                'language_id' => $value->id,
                'category_id' => $category->id
            ];
        }
        $this->validate($request, $validate_array );
        CategoryTranslation::insert($translated);
        return Redirect()->route('categories')->with($notification);


    }

    public function EditCategory($id)
    {
        $category = DB::table('categories')->where('id', $id)->first();
        $translations = DB::table('categories')
            ->join('category_translations', 'categories.id', 'category_translations.category_id')
//            ->join('language', 'category_translations.language_id', 'language.id')
            ->where('categories.id', $id)
            ->get();
//        dd($translations);

        return view('backend.category.edit', compact('translations','category'));
    }

    public function UpdateCategory(Request $request,$id)
    {

        $data = array();
        $notification = array();
        $data['status'] = $request->status ? 1 : 0;
        foreach ($request->category_name as $language => $category_name) {

            $translation = CategoryTranslation::where('category_id',$id)->where('language_id',$language)->first();
            $translation->category_name = $category_name;
            if ($translation->isDirty()) {
                $validate_array = ['category_name' => 'required|min:1|max:255'.$id];
                $validate_array["$category_name"] = 'required'.$id;
                $this->validate($request, $validate_array );
                $translation->save();
                $notification = array(
                    'message' => 'Category Edited successfully',
                    'alert-type' => 'success'
                );
            }

        }
        DB::table('categories')->where('id',$id)->update($data);

        return Redirect()->route('categories')->with($notification);
    }
    public function DeleteCategory($id)
    {
        $category=DB::table('categories')->where('id',$id)->delete();
        $notification = array(
            'message' => 'Category Deleted successfully',
            'alert-type' => 'error'
        );
        return redirect()->route('categories')->with($notification);
    }
}

resources/views/backend/roles/create.blade.php
@extends('admin.admin_master')
@section('admin')



    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 grid-margin stretch-card">
                <div class="card corona-gradient-card">
                    <div class="card-body py-0 px-0 px-sm-3">
                        <div class="row align-items-center">
                            <div class="col-4 col-sm-3 col-xl-2">
                                <img src="{{asset('backend/assets/images/dashboard/Group126@2x.png')}}"
                                     class="gradient-corona-img img-fluid" alt="">
                            </div>
                            <div class="col-5 col-sm-7 col-xl-8 p-0">
                                <h4 class="mb-1 mb-sm-0">Welcome to Easy News </h4>

                            </div>
                            <div class="col-3 col-sm-2 col-xl-2 pl-0 text-center">
                        <span>
        <a href=" {{ url('/') }} " target="_blank" class="btn btn-outline-light btn-rounded get-started-btn">Vist Fontend ? </a>
                        </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">

            <div class="col-lg-12 margin-tb">

                <div class="pull-left">

                    <h2>Create New User</h2>

                </div>

                <div class="pull-right">

                    <a class="btn btn-primary" href="{{ route('users.index') }}"> Back</a>

                </div>

            </div>

        </div>



        @if (count($errors) > 0)

            <div class="alert alert-danger">

                <strong>Whoops!</strong> There were some problems with your input.<br><br>

                <ul>

                    @foreach ($errors->all() as $error)

                        <li>{{ $error }}</li>

                    @endforeach

                </ul>

            </div>

        @endif


        {!! Form::open(array('route' => 'roles.store','method'=>'POST')) !!}

        <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Name:</strong>

                    {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}

                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Permission:</strong>

                    <br/>

                    @foreach($permission as $value)

                        <label>{{ Form::checkbox('permission[]', $value->id, false, array('class' => 'name')) }}

                            {{ $value->name }}</label>

                        <br/>

                    @endforeach

                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">

                <button type="submit" class="btn btn-primary">Submit</button>

            </div>

        </div>

    {!! Form::close() !!}

@endsection

resources/views/backend/roles/edit.blade.php
@extends('admin.admin_master')
@section('admin')



    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 grid-margin stretch-card">
                <div class="card corona-gradient-card">
                    <div class="card-body py-0 px-0 px-sm-3">
                        <div class="row align-items-center">
                            <div class="col-4 col-sm-3 col-xl-2">
                                <img src="{{asset('backend/assets/images/dashboard/Group126@2x.png')}}" class="gradient-corona-img img-fluid" alt="">
                            </div>
                            <div class="col-5 col-sm-7 col-xl-8 p-0">
                                <h4 class="mb-1 mb-sm-0">Welcome to Easy News </h4>

                            </div>
                            <div class="col-3 col-sm-2 col-xl-2 pl-0 text-center">
                        <span>
        <a href=" {{ url('/') }} " target="_blank" class="btn btn-outline-light btn-rounded get-started-btn">Vist Fontend ? </a>
                        </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>



        <div class="row">

            <div class="col-lg-12 margin-tb">

                <div class="pull-left">

                    <h2>Edit Role</h2>

                </div>

                <div class="pull-right">

                    <a class="btn btn-primary" href="{{ route('roles.index') }}"> Back</a>

                </div>

            </div>

        </div>



        @if (count($errors) > 0)

            <div class="alert alert-danger">

                <strong>Whoops!</strong> There were some problems with your input.<br><br>

                <ul>

                    @foreach ($errors->all() as $error)

                        <li>{{ $error }}</li>

                    @endforeach

                </ul>

            </div>

        @endif



        {!! Form::model($role, ['method' => 'PATCH','route' => ['roles.update', $role->id]]) !!}

        <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Name:</strong>

                    {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}

                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Permission:</strong>

                    <br/>

                    @foreach($permission as $value)

                        <label>{{ Form::checkbox('permission[]', $value->id, in_array($value->id, $rolePermissions) ? true : false, array('class' => 'name')) }}

                            {{ $value->name }}</label>

                        <br/>

                    @endforeach

                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">

                <button type="submit" class="btn btn-primary">Submit</button>

            </div>

        </div>

    {!! Form::close() !!}
@endsection

resources/views/backend/roles/index.blade.php
@extends('admin.admin_master')
@section('admin')


    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 grid-margin stretch-card">
                <div class="card corona-gradient-card">
                    <div class="card-body py-0 px-0 px-sm-3">
                        <div class="row align-items-center">
                            <div class="col-4 col-sm-3 col-xl-2">
                                <img src="{{asset('backend/assets/images/dashboard/Group126@2x.png')}}" class="gradient-corona-img img-fluid" alt="">
                            </div>
                            <div class="col-5 col-sm-7 col-xl-8 p-0">
                                <h4 class="mb-1 mb-sm-0">Welcome to Easy News </h4>

                            </div>
                            <div class="col-3 col-sm-2 col-xl-2 pl-0 text-center">
                        <span>
        <a href=" {{ url('/') }} " target="_blank" class="btn btn-outline-light btn-rounded get-started-btn">Visit Fontend ? </a>
                        </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">

            <div class="col-lg-12 margin-tb">

                <div class="pull-left">

                    <h2>Role Management</h2>

                </div>

                <div class="pull-right">

                    @can('role-create')

                        <a class="btn btn-success" href="{{ route('roles.create') }}"> Create New Role</a>

                    @endcan

                </div>

            </div>

        </div>



        @if ($message = Session::get('success'))

            <div class="alert alert-success">

                <p>{{ $message }}</p>

            </div>

        @endif



        <table class="table table-bordered">

            <tr>

                <th>No</th>

                <th>Name</th>

                <th width="280px">Action</th>

            </tr>

            @foreach ($roles as $key => $role)

                <tr>

                    <td>{{ ++$i }}</td>

                    <td>{{ $role->name }}</td>

                    <td>

                        <a class="btn btn-info" href="{{ route('roles.show',$role->id) }}">Show</a>

                        @can('role-edit')

                            <a class="btn btn-primary" href="{{ route('roles.edit',$role->id) }}">Edit</a>

                        @endcan

                        @can('role-delete')

                            {!! Form::open(['method' => 'DELETE','route' => ['roles.destroy', $role->id],'style'=>'display:inline']) !!}

                            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}

                            {!! Form::close() !!}

                        @endcan

                    </td>

                </tr>

            @endforeach

        </table>



    {!! $roles->render() !!}
@endsection

resources/views/backend/roles/show.blade.php
@extends('admin.admin_master')
@section('admin')


    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 grid-margin stretch-card">
                <div class="card corona-gradient-card">
                    <div class="card-body py-0 px-0 px-sm-3">
                        <div class="row align-items-center">
                            <div class="col-4 col-sm-3 col-xl-2">
                                <img src="{{asset('backend/assets/images/dashboard/Group126@2x.png')}}" class="gradient-corona-img img-fluid" alt="">
                            </div>
                            <div class="col-5 col-sm-7 col-xl-8 p-0">
                                <h4 class="mb-1 mb-sm-0">Welcome to Easy News </h4>

                            </div>
                            <div class="col-3 col-sm-2 col-xl-2 pl-0 text-center">
                        <span>
        <a href=" {{ url('/') }} " target="_blank" class="btn btn-outline-light btn-rounded get-started-btn">Visit Fontend ? </a>
                        </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">

            <div class="col-lg-12 margin-tb">

                <div class="pull-left">

                    <h2> Show Role</h2>

                </div>

                <div class="pull-right">

                    <a class="btn btn-primary" href="{{ route('roles.index') }}"> Back</a>

                </div>

            </div>

        </div>



        <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Name:</strong>

                    {{ $role->name }}

                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Permissions:</strong>

                    @if(!empty($rolePermissions))

                        @foreach($rolePermissions as $v)

                            <label class="label label-success">{{ $v->name }},</label>

                        @endforeach

                    @endif

                </div>

            </div>

        </div>

@endsection