routes/web.php
    Route::post('/segment/save', [SegmentController::class, 'StoreSegment'])->name('store.category_segment');
    Route::post('/segment/update', [SegmentController::class, 'UpdateSegment'])->name('update.segment');
    Route::get('/delete/segment/{id}', [SegmentController::class, 'DeleteSegment'])->name('delete.segment');

});

//Admin Subcategory
Route::get('/subcategories', [SubCategoryController::class, 'Index'])->name('subcategories');
Route::get('/add/subcategory', [SubCategoryController::class, 'AddSubCategory'])->name('add.subcategory');
Route::get('/edit/subcategory/{id}', [SubCategoryController::class, 'EditSubCategory'])->name('edit.subcategory');
Route::post('/store/subcategory', [SubCategoryController::class, 'StoreSubCategory'])->name('store.subcategory');
Route::post('/update/subcategory/{id}', [SubCategoryController::class, 'UpdateSubCategory'])->name('update.subcategory');
Route::get('/delete/subcategory/{id}', [SubCategoryController::class, 'DeleteSubCategory'])->name('delete.subcategory');
//Route::get('/delete/subcategory/{id}', [SubCategoryController::class, 'DeleteSubCategory'])->name('delete.subcategory');


Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
//Admin Post
    Route::get('/all/lang', [LanguageController::class, 'Index'])->name('language.all');
    Route::get('/create/lang', [LanguageController::class, 'Create'])->name('language.create');
    Route::post('/store/lang', [LanguageController::class, 'Store'])->name('language.store');
    Route::get('/edit/lang/{id}', [LanguageController::class, 'Edit'])->name('language.edit');
    Route::get('pages/config/edittranslation{edit?}', [LanguageController::class, 'EditTranslation'])->name('translation.edit');
    Route::post('/save/translation', [LanguageController::class, 'SaveTranslation'])->name('translation.save');
    Route::get('/language/delete/{id}', [LanguageController::class, 'Delete'])->name('language.delete');
    Route::post('/language/update/{id}', [LanguageController::class, 'Update'])->name('language.update');

    Route::get('/create/post', [PostController::class, 'Create'])->name('create.post');
    Route::post('/store/post', [PostController::class, 'StorePost'])->name('store.post');
    Route::get('/all_post', [PostController::class, 'Index'])->name('all.post');
    Route::get('/edit_post/{id}', [PostController::class, 'EditPost'])->name('edit.post');
    Route::get('/delete_post/{id}', [PostController::class, 'DeletePost'])->name('delete.post');
    Route::post('/update/post/{id}', [PostController::class, 'UpdatePost'])->name('update.post');
});




//About us
Route::get('/website/aboutUs', [AboutUsController::class, 'Index'])->name('AboutUs');

//settings
Route::get('/social/setting', [SettingController::class, 'SocialSetting'])->name('social.setting');
Route::post('/social/update/{id?}', [SettingController::class, 'SocialUpdate'])->name('update.social');
Route::get('/seo/setting', [SettingController::class, 'SeoSetting'])->name('seo.setting');
Route::post('/seo/update/{id}', [SettingController::class, 'SeoUpdate'])->name('update.seo');
Route::get('/live_tv/setting', [SettingController::class, 'LiveTvSetting'])->name('live_tv.setting');
Route::post('/live_tv/update/{id}', [SettingController::class, 'LiveTvUpdate'])->name('update.live_tv');
//live_tv active inactive
Route::get('/live_tv/active/{id}', [SettingController::class, 'Active_LiveTV'])->name('active.live_tv');
Route::get('/live_tv/inactive/{id}', [SettingController::class, 'Inactive_LiveTV'])->name('inactive.live_tv');
Route::get('/notice/setting', [SettingController::class, 'NoticeSetting'])->name('notice.setting');
Route::post('/notice/update/{id}', [SettingController::class, 'NoticeUpdate'])->name('update.notice');
Route::get('/notice/active/{id}', [SettingController::class, 'ActiveNoticeSetting'])->name('active.notice');
Route::get('/notice/inactive/{id}', [SettingController::class, 'InActiveNoticeSetting'])->name('inactive.notice');

//Website
Route::get('/website/setting', [SettingController::class, 'WebsiteSetting'])->name('all.website');
Route::get('/logo/setting', [SettingController::class, 'Logo'])->name('settings');
Route::get('/logo/edit/{id}', [SettingController::class, 'LogoEdit'])->name('settings.edit.logo');
Route::post('/logo/update/{id}', [SettingController::class, 'LogoUpdate'])->name('settings.update.logo');
Route::get('/add/website', [SettingController::class, 'AddWebsiteSetting'])->name('add.website');
Route::post('/store/website', [SettingController::class, 'StoreWebsite'])->name('store.website');
Route::get('/edit_website/{id}', [SettingController::class, 'EditWebsite'])->name('edit.website');
Route::post('/update/website/{id}', [SettingController::class, 'UpdateWebsite'])->name('update.website');
Route::get('/delete_website/{id}', [SettingController::class, 'DeleteWebsite'])->name('delete.website');

//Gallery
Route::get('/photo/gallery', [GalleryController::class, 'PhotoGallery'])->name('photo.gallery');
Route::get('/add/photo', [GalleryController::class, 'AddPhoto'])->name('add.photo');
Route::post('/store/photo', [GalleryController::class, 'StorePhoto'])->name('store.photo');
Route::get('/edit_photo/{id}', [GalleryController::class, 'EditPhoto'])->name('edit.photo');
Route::post('/update/photo/{id}', [GalleryController::class, 'UpdatePhoto'])->name('update.photo');
Route::get('/delete_photo/{id}', [GalleryController::class, 'DeletePhoto'])->name('delete.photo');

Route::get('/video/gallery', [GalleryController::class, 'VideoGallery'])->name('video.gallery');
Route::get('/add/video', [GalleryController::class, 'AddVideo'])->name('add.video');
Route::post('/store/video', [GalleryController::class, 'StoreVideo'])->name('store.video');
Route::get('/edit_video/{id}', [GalleryController::class, 'EditVideo'])->name('edit.video');
Route::post('/update/video/{id}', [GalleryController::class, 'UpdateVideo'])->name('update.video');
Route::get('/delete_video/{id}', [GalleryController::class, 'DeleteVideo'])->name('delete.video');

Route::get('/add/writer', [RoleController::class, 'InsertWriter'])->name('add.writer');
Route::get('/allWriters', [RoleController::class, 'AllWriter'])->name('all.writer');
Route::get('/users', [UserController::class, 'Index'])->name('users.index');
Route::post('/store/writer', [RoleController::class, 'StoreWriter'])->name('store.writer');
Route::get('/edit/role/{id}', [RoleController::class, 'EditWriter'])->name('edit.writer');
Route::post('/update/writer/{id}', [RoleController::class, 'UpdateWriter'])->name('update.writer');
Route::get('/delete/role/{id}', [GalleryController::class, 'DeleteVideo'])->name('delete.writer');


//Route::resource('lang',AdminController::class);
//Route::get('GetLang',function ()
//{
//    return view('backend.admin.body.header');
//});
//Single Post
//Post Category and SubCategory single pages


//Ads Backend Section
Route::get('/ad/list', [AdsController::class, 'AdList'])->name('ad.list');
Route::get('/ad/add', [AdsController::class, 'Create'])->name('ad.add');
Route::post('/store/ad', [AdsController::class, 'Store'])->name('store.ads');


Route::group(["prefix"=> 'subscribers'],function ()
{
    Route::get('/', [SubscribeController::class, 'index'])->name('subscriber.index');
});



//Lang


Route::get('/contact-form', [ContactController::class, 'contactForm'])->name('contact-form');
Route::post('/contact-form', [ContactController::class, 'storeContactForm'])->name('contact-form.store');
Route::post('/subscribe/store',[SubscribeController::class,'store'])->name('subscriber.store');
Route::post('/subscribe/store',[SubscribeController::class,'store'])->name('subscriber.store');
//Route::get('/compose', [SubscribeController::class, 'compose']);
//Route::post('/send', [EmailController::class, 'send']);


Route::group(['prefix'=>LaravelLocalization::setLocale(),
    'as'=>'front.',
    'middleware'=>['localeSessionRedirect','localizationRedirect',]],function ()
{
    Route::get('/', function () {
        return view('main.home');
    });

    Route::get('/catposts/{id}', [ExtraController::class, 'CatPost'])->name('catPost');
    Route::get('/subcatposts/{id}', [ExtraController::class, 'SubCatPost'])->name('subCatPost');
    Route::get('/area_post/{id}',[ExtraController::class,'AreaPost'])->name('areaPosts');
    Route::get('/aboutUs/',[ExtraController::class,'AboutUs'])->name('aboutUs');
    Route::get('/search/', [ExtraController::class, 'search'])->name('search');
    Route::get('/lastNews/', [ExtraController::class, 'LastNews'])->name('lastNews');
    Route::get('/lastNews/today', [ExtraController::class, 'LastNewsToday'])->name('lastNewsToday');
    Route::get('/lastNews/yesterday', [ExtraController::class, 'LastNewsYesterday'])->name('lastNewsYesterday');
    Route::get('/lastNews/thisWeek', [ExtraController::class, 'LastNewsThisWeek'])->name('lastNewsThisWeek');
    Route::get('/lastNews/thisMonth', [ExtraController::class, 'LastNewsThisMonth'])->name('lastNewsThisMonth');
    Route::get('/lastNews/prevWeek', [ExtraController::class, 'LastNewsPrevWeek'])->name('lastNewsPrevWeek');
    Route::get('/lastNews/lastMonth', [ExtraController::class, 'LastNewsLastMonth'])->name('lastNewsLastMonth');
    Route::get('/videoNews', [ExtraController::class, 'VideoNews'])->name('videoNews');
    Route::get('/photoNews', [ExtraController::class, 'PhotoNews'])->name('photoNews');
    Route::get('/areaNews', [ExtraController::class, 'AreaNews'])->name('areaNews');
    Route::get('/multimedia', [ExtraController::class, 'MultiMedia'])->name('multiMedia');
    Route::get('/contact/', [ExtraController::class, 'contact'])->name('contact');
    Route::get('/view/post/{id}', [ExtraController::class, 'SinglePost'])->name('post_view');
    Route::get('/{lang}',[LanguageController::class,'GetChange'])->name('change');
    Route::get('/',[FrontendController::class,'Home'])->name('getHome');

resources/views/main/body/footer.blade.php
<!-- Footer -->
<footer class="footer">
    <div class="footer__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-12">

                    <a href=""><img src="  {{asset('frontend/assets/img/logo-white.svg')}}" alt="" class="footer__logo img-fluid"></a>
                </div>
                <div class="col-lg-5 col-md-4 col-sm-6">
                    <h3 class="footer__title">{{trans('front.categories')}}</h3>
                    <ul class="footer__list">
                        <li><a href="{{url('/')}}" class="footer__list-link">{{trans('front.main news')}}</a></li>
                        <li><a href="{{route('front.lastNews')}}" class="footer__list-link">{{trans('front.latest news')}}</a></li>
                        @foreach($category_head as $cat)
                            <li><a href="{{( route('front.catPost',['id'=>$cat->id] ) )}}" class="footer__list-link">{{$cat->category_name}}</a></li>
                        @endforeach
                    </ul>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-3 col-6">
                    <h3 class="footer__title">{{trans('front.multimedia')}}</h3>
                    <ul class="footer__list">
                        <li><a href="{{route('front.photoNews')}}" class="footer__list-link">{{trans('front.photo')}}</a></li>
                        <li><a href="{{route('front.videoNews')}}" class="footer__list-link">{{trans('front.video')}}</a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-3 col-6">
                    <h3 class="footer__title">{{trans('front.contact_us')}}</h3>
                    <ul class="nav__social-list">
                        <li>
                            <a href="#" target="_blank"><i ></i></a>
                        </li>
                        @if($socials_head)
                            @if($socials_head->facebook!=null)
                                <a href="{{$socials_head->facebook}}" target="_blank"><i class="so-facebook"></i></a>
                            @endif
                            @if($socials_head->twitter!=null)
                                <a href="{{$socials_head->twitter}}" target="_blank"><i class="so-twitter"></i></a>
                            @endif
                            {{--                                    @if($socials_head->youtube!=null)--}}
                            {{--                                        <a href="{{$socials_head->youtube}}" target="_blank"><i class="so-youtube"></i></a>--}}
                            {{--                                    @endif--}}
                            @if($socials_head->linkedin!=null)
                                <a href="{{$socials_head->linkedin}}" target="_blank"><i class="so-linkedin"></i></a>
                            @endif
                            @if($socials_head->instagram!=null)
                                <a href="{{$socials_head->instagram}}" target="_blank"><i class="so-instagram"></i></a>
                            @endif
                        @endif
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="footer__bottom">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-auto">
                    <span class="footer__copyright">© 2020 Pronews Company</span>
                </div>
                <div class="col-auto">
                    <a href="{{( route('front.aboutUs' ))}}" class="footer__about">{{trans('front.about_us')}}</a>
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- /.Footer -->

resources/views/main/body/header.blade.php
<!-- Header -->
<header class="header">
    <div class="nav__info d-none d-lg-block">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-md-7">
                    <div class="nav__info-left">
                        <div class="nav__info-weather">
                            <i class="so-cloudy"></i>

                            <span>Bakı 14° C – 4 m/s</span>
                        </div>
                        <div class="nav__info-currecny">
                            <ul class="nav__currency-list">
                                <li>USD - 1.7000</li>
                                <li>EUR - 1.9956</li>
                                <li>RUB - 0.0219</li>
                                <li>BRENT - 42.44</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 d-flex justify-content-end">
                    <div class="nav__info-right">
                        <div class="nav__info-social">
                            <ul class="nav__social-list">
                                <li>
                                    <a href="#" target="_blank"><i ></i></a>
                                </li>
                                @if($socials_head)
                                    @if($socials_head->facebook!=null)
                                        <a href="{{$socials_head->facebook}}" target="_blank"><i class="so-facebook"></i></a>
                                    @endif
                                    @if($socials_head->twitter!=null)
                                        <a href="{{$socials_head->twitter}}" target="_blank"><i class="so-twitter"></i></a>
                                    @endif
{{--                                    @if($socials_head->youtube!=null)--}}
{{--                                        <a href="{{$socials_head->youtube}}" target="_blank"><i class="so-youtube"></i></a>--}}
{{--                                    @endif--}}
                                    @if($socials_head->linkedin!=null)
                                        <a href="{{$socials_head->linkedin}}" target="_blank"><i class="so-linkedin"></i></a>
                                    @endif
                                    @if($socials_head->instagram!=null)
                                        <a href="{{$socials_head->instagram}}" target="_blank"><i class="so-instagram"></i></a>
                                    @endif
                                @endif
                            </ul>
                        </div>

                        <div class="nav__info-about">
                            <a href="{{( route('front.aboutUs' ))}}" class="nav__info-link">{{trans('front.about_us')}}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="nav__main">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="col-auto">
                    <div class="nav__main-left">
                        <a href="/"><img src="{{asset('frontend/assets/img/logo.svg')}}" class="img-fluid nav__main-logo" alt="ProNews.az"></a>
                    </div>
                </div>
                <div class="col-auto">
                    <div class="nav__main-right">

                        <form action="{{ route('front.search')}}" method="GET">
                            <input type="text" name="search" id="search-input" class="nav__main-search-input" placeholder="{{trans('front.search')}}...">
                        </form>

                        <a href="javascript:void(0);" class="nav__main-search">
                            <i class="so-search"></i>
                        </a>
                        <a href="javascript:void(0);" class="nav__burger d-lg-none d-flex"><span class="nav__burger-line"></span></a>
                        <div class="nav__language d-none d-lg-block">
                            <a href="javascript:void(0);" class="nav__language-link dropdownButton">{{app()->getLocale()}}<i
                                    class="so-arrow-down"></i></a>
                            @foreach($languages as $key=>$lang)
                            <ul class="nav__language-list dropdownMenu">
                                <li class="nav__language-item">
                                    <a href="{{LaravelLocalization::getLocalizedURL($lang->code, null, [], true)}}">{{$lang->code}}</a>
                                </li>

                            </ul>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="nav__categories d-none d-lg-block">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <ul class="nav__categories-list">
                        <li><a href="{{url('/')}}" class="nav__categories-link">{{trans('front.main news')}}</a></li>
                        <li><a href="{{route('front.lastNews')}}" class="nav__categories-link">{{trans('front.latest news')}}</a></li>
                        @foreach($category_head as $cat)
                            <li><a href="{{( route('front.catPost',['id'=>$cat->id] ) )}}" class="nav__categories-link">{{$cat->category_name}}</a></li>
                        @endforeach
                        <li><a href="{{route('front.multiMedia')}}" class="nav__categories-link">{{trans('front.multimedia')}}</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="nav__burger-menu-wrapper">
        <div class="nav__burger-menu-overlay"></div>
        <div class="nav__burger-menu">
            <a href="javascript:void(0);" class="nav__burger-close"><i class="so-close"></i></a>
            <div class="nav__burger-header">
                <div class="nav__burger-weather"></div>
                <div class="nav__burger-languages"></div>
            </div>
            <div class="nav__burger-content"></div>
            <div class="nav__burger-footer">
                <div class="nav__burger-about"></div>
                <div class="nav__burger-social"></div>
            </div>
        </div>
    </div>
</header>
<!-- /.Header -->