routes/web.php
    Route::post('/segment/save', [SegmentController::class, 'StoreSegment'])->name('store.category_segment');
    Route::post('/segment/update', [SegmentController::class, 'UpdateSegment'])->name('update.segment');
    Route::get('/delete/segment/{id}', [SegmentController::class, 'DeleteSegment'])->name('delete.segment');

});

//Admin Subcategory
Route::get('/subcategories', [SubCategoryController::class, 'Index'])->name('subcategories');
Route::get('/add/subcategory', [SubCategoryController::class, 'AddSubCategory'])->name('add.subcategory');
Route::get('/edit/subcategory/{id}', [SubCategoryController::class, 'EditSubCategory'])->name('edit.subcategory');
Route::post('/store/subcategory', [SubCategoryController::class, 'StoreSubCategory'])->name('store.subcategory');
Route::post('/update/subcategory/{id}', [SubCategoryController::class, 'UpdateSubCategory'])->name('update.subcategory');
Route::get('/delete/subcategory/{id}', [SubCategoryController::class, 'DeleteSubCategory'])->name('delete.subcategory');
//Route::get('/delete/subcategory/{id}', [SubCategoryController::class, 'DeleteSubCategory'])->name('delete.subcategory');


Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
//Admin Post
    Route::get('/all/lang', [LanguageController::class, 'Index'])->name('language.all');
    Route::get('/create/lang', [LanguageController::class, 'Create'])->name('language.create');
    Route::post('/store/lang', [LanguageController::class, 'Store'])->name('language.store');
    Route::get('/edit/lang/{id}', [LanguageController::class, 'Edit'])->name('language.edit');
    Route::get('pages/config/edittranslation{edit?}', [LanguageController::class, 'EditTranslation'])->name('translation.edit');
    Route::post('/save/translation', [LanguageController::class, 'SaveTranslation'])->name('translation.save');
    Route::get('/language/delete/{id}', [LanguageController::class, 'Delete'])->name('language.delete');
    Route::post('/language/update/{id}', [LanguageController::class, 'Update'])->name('language.update');

    Route::get('/create/post', [PostController::class, 'Create'])->name('create.post');
    Route::post('/store/post', [PostController::class, 'StorePost'])->name('store.post');
    Route::get('/all_post', [PostController::class, 'Index'])->name('all.post');
    Route::get('/edit_post/{id}', [PostController::class, 'EditPost'])->name('edit.post');
    Route::get('/delete_post/{id}', [PostController::class, 'DeletePost'])->name('delete.post');
    Route::post('/update/post/{id}', [PostController::class, 'UpdatePost'])->name('update.post');
});




//About us
Route::get('/website/aboutUs', [AboutUsController::class, 'Index'])->name('AboutUs');

//settings
Route::get('/social/setting', [SettingController::class, 'SocialSetting'])->name('social.setting');
Route::post('/social/update/{id?}', [SettingController::class, 'SocialUpdate'])->name('update.social');
Route::get('/seo/setting', [SettingController::class, 'SeoSetting'])->name('seo.setting');
Route::post('/seo/update/{id}', [SettingController::class, 'SeoUpdate'])->name('update.seo');
Route::get('/live_tv/setting', [SettingController::class, 'LiveTvSetting'])->name('live_tv.setting');
Route::post('/live_tv/update/{id}', [SettingController::class, 'LiveTvUpdate'])->name('update.live_tv');
//live_tv active inactive
Route::get('/live_tv/active/{id}', [SettingController::class, 'Active_LiveTV'])->name('active.live_tv');
Route::get('/live_tv/inactive/{id}', [SettingController::class, 'Inactive_LiveTV'])->name('inactive.live_tv');
Route::get('/notice/setting', [SettingController::class, 'NoticeSetting'])->name('notice.setting');
Route::post('/notice/update/{id}', [SettingController::class, 'NoticeUpdate'])->name('update.notice');
Route::get('/notice/active/{id}', [SettingController::class, 'ActiveNoticeSetting'])->name('active.notice');
Route::get('/notice/inactive/{id}', [SettingController::class, 'InActiveNoticeSetting'])->name('inactive.notice');

//Website
Route::get('/website/setting', [SettingController::class, 'WebsiteSetting'])->name('all.website');
Route::get('/logo/setting', [SettingController::class, 'Logo'])->name('settings');
Route::get('/logo/edit/{id}', [SettingController::class, 'LogoEdit'])->name('settings.edit.logo');
Route::post('/logo/update/{id}', [SettingController::class, 'LogoUpdate'])->name('settings.update.logo');
Route::get('/add/website', [SettingController::class, 'AddWebsiteSetting'])->name('add.website');
Route::post('/store/website', [SettingController::class, 'StoreWebsite'])->name('store.website');
Route::get('/edit_website/{id}', [SettingController::class, 'EditWebsite'])->name('edit.website');
Route::post('/update/website/{id}', [SettingController::class, 'UpdateWebsite'])->name('update.website');
Route::get('/delete_website/{id}', [SettingController::class, 'DeleteWebsite'])->name('delete.website');

//Gallery
Route::get('/photo/gallery', [GalleryController::class, 'PhotoGallery'])->name('photo.gallery');
Route::get('/add/photo', [GalleryController::class, 'AddPhoto'])->name('add.photo');
Route::post('/store/photo', [GalleryController::class, 'StorePhoto'])->name('store.photo');
Route::get('/edit_photo/{id}', [GalleryController::class, 'EditPhoto'])->name('edit.photo');
Route::post('/update/photo/{id}', [GalleryController::class, 'UpdatePhoto'])->name('update.photo');
Route::get('/delete_photo/{id}', [GalleryController::class, 'DeletePhoto'])->name('delete.photo');

Route::get('/video/gallery', [GalleryController::class, 'VideoGallery'])->name('video.gallery');
Route::get('/add/video', [GalleryController::class, 'AddVideo'])->name('add.video');
Route::post('/store/video', [GalleryController::class, 'StoreVideo'])->name('store.video');
Route::get('/edit_video/{id}', [GalleryController::class, 'EditVideo'])->name('edit.video');
Route::post('/update/video/{id}', [GalleryController::class, 'UpdateVideo'])->name('update.video');
Route::get('/delete_video/{id}', [GalleryController::class, 'DeleteVideo'])->name('delete.video');

Route::get('/add/writer', [RoleController::class, 'InsertWriter'])->name('add.writer');
Route::get('/allWriters', [RoleController::class, 'AllWriter'])->name('all.writer');
Route::get('/users', [UserController::class, 'Index'])->name('users.index');
Route::post('/store/writer', [RoleController::class, 'StoreWriter'])->name('store.writer');
Route::get('/edit/role/{id}', [RoleController::class, 'EditWriter'])->name('edit.writer');
Route::post('/update/writer/{id}', [RoleController::class, 'UpdateWriter'])->name('update.writer');
Route::get('/delete/role/{id}', [GalleryController::class, 'DeleteVideo'])->name('delete.writer');


//Route::resource('lang',AdminController::class);
//Route::get('GetLang',function ()
//{
//    return view('backend.admin.body.header');
//});
//Single Post
//Post Category and SubCategory single pages


//Ads Backend Section
Route::get('/ad/list', [AdsController::class, 'AdList'])->name('ad.list');
Route::get('/ad/add', [AdsController::class, 'Create'])->name('ad.add');
Route::post('/store/ad', [AdsController::class, 'Store'])->name('store.ads');


Route::group(["prefix"=> 'subscribers'],function ()
{
    Route::get('/', [SubscribeController::class, 'index'])->name('subscriber.index');
});



//Lang


Route::get('/contact-form', [ContactController::class, 'contactForm'])->name('contact-form');
Route::post('/contact-form', [ContactController::class, 'storeContactForm'])->name('contact-form.store');
Route::post('/subscribe/store',[SubscribeController::class,'store'])->name('subscriber.store');
Route::post('/subscribe/store',[SubscribeController::class,'store'])->name('subscriber.store');
//Route::get('/compose', [SubscribeController::class, 'compose']);
//Route::post('/send', [EmailController::class, 'send']);


Route::group(['prefix'=>LaravelLocalization::setLocale(),
    'as'=>'front.',
    'middleware'=>['localeSessionRedirect','localizationRedirect',]],function ()
{
    Route::get('/', function () {
        return view('main.home');
    });

    Route::get('/catposts/{id}', [ExtraController::class, 'CatPost'])->name('catPost');
    Route::get('/subcatposts/{id}', [ExtraController::class, 'SubCatPost'])->name('subCatPost');
    Route::get('/area_post/{id}',[ExtraController::class,'AreaPost'])->name('areaPosts');
    Route::get('/aboutUs/',[ExtraController::class,'AboutUs'])->name('aboutUs');
    Route::get('/search/', [ExtraController::class, 'search'])->name('search');
    Route::get('/lastNews/', [ExtraController::class, 'LastNews'])->name('lastNews');
    Route::get('/lastNews/today', [ExtraController::class, 'LastNewsToday'])->name('lastNewsToday');
    Route::get('/lastNews/yesterday', [ExtraController::class, 'LastNewsYesterday'])->name('lastNewsYesterday');
    Route::get('/lastNews/thisWeek', [ExtraController::class, 'LastNewsThisWeek'])->name('lastNewsThisWeek');
    Route::get('/lastNews/thisMonth', [ExtraController::class, 'LastNewsThisMonth'])->name('lastNewsThisMonth');
    Route::get('/lastNews/prevWeek', [ExtraController::class, 'LastNewsPrevWeek'])->name('lastNewsPrevWeek');
    Route::get('/lastNews/lastMonth', [ExtraController::class, 'LastNewsLastMonth'])->name('lastNewsLastMonth');
    Route::get('/videoNews', [ExtraController::class, 'VideoNews'])->name('videoNews');
    Route::get('/photoNews', [ExtraController::class, 'PhotoNews'])->name('photoNews');
    Route::get('/areaNews', [ExtraController::class, 'AreaNews'])->name('areaNews');
    Route::get('/multimedia', [ExtraController::class, 'MultiMedia'])->name('multiMedia');
    Route::get('/contact/', [ExtraController::class, 'contact'])->name('contact');
    Route::get('/view/post/{id}', [ExtraController::class, 'SinglePost'])->name('post_view');
    Route::get('/{lang}',[LanguageController::class,'GetChange'])->name('change');
    Route::get('/',[FrontendController::class,'Home'])->name('getHome');

resources/views/main/aboutUs.blade.php
@extends('main.home_master')

@section('title')
    {{trans('front.about_us')}}
@endsection

@section('css')
@endsection

@section('content')
    <!-- Menu Section Start -->
@if(isset($aboutUs))
    {!!     $aboutUs->about_us_translation !!}
@endif
@endsection

@section('js')
@endsection

resources/views/main/allAreaPosts.blade.php
@extends('main.home_master')
@section('content')
    <!-- Menu Section Start -->


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="{{asset('frontend/assets//js/jquery.jscroll.min.js')}}"fro></script>

    <!-- Post Section Start -->
    <section class="categories-news">
        <div class="container">
            <div class="row">

                @foreach($areaPosts as $cp)

                    <div class="col-sm-3 col-6">
                        <div class="news-block__medium news-block__medium_media news-block__medium_region">
                            <a href=""><img src="{{url($cp->image)}}" alt="" class="news-block__image img-fluid"></a>
                            <div class="news-block__info-wrapper">
                                <div class="news-block__info">
                                    <a href="" class="news-block__info-link">{{$cp->title}}|{{$cp->area_name}}</a>
                                    <span
                                        class="news-block__date">{{\App\Models\Post::DateTranslate($cp->post_date)}}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
        <script type="text/javascript">
            $('ul.pagination').hide();
            $(function() {
                $('.infinite-scroll').jscroll({
                    autoTrigger: true,
                    loadingHtml: '<img class="center-block" src="/images/loading.gif" alt="Loading..." />',
                    padding: 0,
                    nextSelector: '.pagination li.active + li a',
                    contentSelector: 'div.infinite-scroll',
                    callback: function() {
                        $('ul.pagination').remove();
                    }
                });
            });
        </script>
    </section>
@endsection

resources/views/main/allpost.blade.php
@extends('main.home_master')
@section('content')
    <!-- Menu Section Start -->


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="{{asset('frontend/assets//js/jquery.jscroll.min.js')}}"></script>

    <!-- Post Section Start -->
    <section class="categories-news">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2 class="categories-news__title">{{$cat_name->category_name}}</h2>
                </div>

                <div class="col-12">
                    <div class="infinite-scroll">
                        <ul class="region-news__button-list">

                            @foreach($sub_cat as $sub)
                                <li><a href="{{route('front.subCatPost', [$sub->id])}}"
                                       class="region-news__button">{{$sub->subcategory_name}}</a></li>
                            @endforeach

                        </ul>
                    </div>
                </div>

                @foreach($catposts as $cp)

                    <div class="col-sm-3 col-6">
                        <div class="news-block__medium news-block__medium_media news-block__medium_region">
                            <a href=""><img src="{{url($cp->image)}}" alt="" class="news-block__image img-fluid"></a>
                            <div class="news-block__info-wrapper">
                                <div class="news-block__info">
                                    <a href="" class="news-block__info-link">{{$cp->title}}</a>
                                    <span
                                        class="news-block__date">{{\App\Models\Post::DateTranslate($cp->post_date)}}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
        <script type="text/javascript">
            $('ul.pagination').hide();
            $(function() {
                $('.infinite-scroll').jscroll({
                    autoTrigger: true,
                    loadingHtml: '<img class="center-block" src="/images/loading.gif" alt="Loading..." />',
                    padding: 0,
                    nextSelector: '.pagination li.active + li a',
                    contentSelector: 'div.infinite-scroll',
                    callback: function() {
                        $('ul.pagination').remove();
                    }
                });
            });
        </script>
    </section>
@endsection

resources/views/main/areaPosts.blade.php
@extends('main.home_master')
@section('content')
    <!-- Menu Section Start -->


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="{{asset('frontend/assets//js/jquery.jscroll.min.js')}}"></script>

    <!-- Post Section Start -->
    <section class="categories-news">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2 class="categories-news__title">{{$area_name->area_name}}</h2>
                </div>

                @foreach($areaPosts as $cp)

                    <div class="col-sm-3 col-6">
                        <div class="news-block__medium news-block__medium_media news-block__medium_region">
                            <a href=""><img src="{{url($cp->image)}}" alt="" class="news-block__image img-fluid"></a>
                            <div class="news-block__info-wrapper">
                                <div class="news-block__info">
                                    <a href="" class="news-block__info-link">{{$cp->title}}</a>
                                    <span
                                        class="news-block__date">{{\App\Models\Post::DateTranslate($cp->post_date)}}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
        <script type="text/javascript">
            $('ul.pagination').hide();
            $(function() {
                $('.infinite-scroll').jscroll({
                    autoTrigger: true,
                    loadingHtml: '<img class="center-block" src="/images/loading.gif" alt="Loading..." />',
                    padding: 0,
                    nextSelector: '.pagination li.active + li a',
                    contentSelector: 'div.infinite-scroll',
                    callback: function() {
                        $('ul.pagination').remove();
                    }
                });
            });
        </script>
    </section>
@endsection

resources/views/main/contact.blade.php
@extends('main.home_master')
@section('content')
    <div class="post-section section">
        <div class="container">

            <!-- Feature Post Row Start -->
            <div class="row">

                <div class="col-lg-12 col-12 mb-50">

                    <!-- Post Block Wrapper Start -->
                    <div class="post-block-wrapper">
                        <div class="head">

                            <!-- Title -->
                            <h4 class="title">Send us a Message.</h4>

                        </div><!-- Post Block Head End -->

                        @if(Session::has('success'))
                            <div class="alert alert-success">
                                {{ Session::get('success') }}
                                @php
                                    Session::forget('success');
                                @endphp
                            </div>
                        @endif
                        <form method="POST" action="{{ route('contact-form.store') }}">

                            {{ csrf_field() }}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <strong>Name:</strong>
                                        <input type="text" name="name" class="form-control" placeholder="Name" value="{{ old('name') }}">
                                        @if ($errors->has('name'))
                                            <span class="text-danger">{{ $errors->first('name') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <strong>Email:</strong>
                                        <input type="text" name="email" class="form-control" placeholder="Email" value="{{ old('email') }}">
                                        @if ($errors->has('email'))
                                            <span class="text-danger">{{ $errors->first('email') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <strong>Subject:</strong>
                                        <input type="text" name="subject" class="form-control" placeholder="Subject" value="{{ old('subject') }}">
                                        @if ($errors->has('subject'))
                                            <span class="text-danger">{{ $errors->first('subject') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <strong>Message:</strong>
                                        <textarea name="message" rows="3" class="form-control">{{ old('message') }}</textarea>
                                        @if ($errors->has('message'))
                                            <span class="text-danger">{{ $errors->first('message') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="form-group text-center">
                                <button class="btn btn-success btn-submit">Save</button>
                            </div>
                        </form>

                        </div><!-- Post Block Body End -->

                    </div>

                </div>
                <div class="single-sidebar col-lg-12 col-md-6 col-12">

                    <div class="sidebar-subscribe">
                        <h4>Subscribe To <br>Our <span>Update</span> News</h4>
                        <!-- Newsletter Form -->
                        @if ($errors->has('email'))
                            <span class="text-danger">{{ $errors->first('email') }}</span>
                        @endif
                        <form action="{{route('subscriber.store')}}" method="post" class="subscribe-form validate">
                            @csrf
                            <div id="mc_embed_signup_scroll">
                                <label for="email" class="d-none">Subscribe to our mailing list</label>
                                <input type="email" value="" name="email" class="email" id="email" placeholder="Your email address">
                                <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->

                                <button type="submit" name="subscribe" class="button">submit</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>

    </div>
@endsection

resources/views/main/home_master.blade.php
<!DOCTYPE html>
<html lang="az">

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
          name="viewport">
    <meta content="ie=edge" http-equiv="X-UA-Compatible">
    <title>@yield('title')</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <meta content="" property="og:title" />
    <meta content="" property="og:description" />
    <meta content="" property="og:image" />
    <meta content="website" property="og:type" />
    <meta content="" property="og:url" />
    <link rel="apple-touch-icon" sizes="180x180" href="{{asset('frontend/assets/img/apple-touch-icon.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{asset('frontend/assets/img/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{asset('frontend/assets/img/favicon-16x16.png')}}">
    <link rel="manifest" href="{{asset('frontend/assets/img/site.webmanifest')}}">
    <link rel="stylesheet" href="{{asset('frontend/assets/css/main.min.css')}}">
    <link rel="stylesheet" href="{{asset('node_modules/air-datepicker/dist/css/datepicker.css')}}">

    @yield('css')
</head>

<body>
@include('main.body.header')
@yield('content')
@include('main.body.footer')


<script src="{{asset('frontend/assets/js/app.min.js')}}"></script>
@yield('js')
</body>

</html>

resources/views/main/lastNews.blade.php
@extends('main.home_master')
@section('content')
    <br>
    <section class="categories-news">
        <div class="container">

            <div class="row">
                <div class="col-12">
                    <ul class="region-news__button-list">
                        <li><a href="{{route('front.lastNewsToday')}}"  class="region-news__button">{{trans('front.today')}}</a></li>
                        <li><a href="{{route('front.lastNewsYesterday')}}"  class="region-news__button">{{trans('front.yesterday')}}</a></li>
                        <li><a href="{{route('front.lastNewsThisWeek')}}"  class="region-news__button">{{trans('front.this_week')}}</a></li>
                        <li><a href="{{route('front.lastNewsThisMonth')}}"  class="region-news__button">{{trans('front.this_month')}}</a></li>
                        <li><a href="{{route('front.lastNewsPrevWeek')}}"  class="region-news__button">{{trans('front.prev_week')}}</a></li>
                        <li><a href="{{route('front.lastNewsLastMonth')}}"  class="region-news__button">{{trans('front.last_month')}}</a></li>
                    </ul>
                </div>
            </div>
            <div class="row">

                @foreach($lastNews as $cp)
                    <div class="col-sm-3 col-6">
                        <div class="news-block__medium news-block__medium_media news-block__medium_region">
                            <a href=""><img src="{{url($cp->image)}}" alt="" class="news-block__image img-fluid"></a>
                            <div class="news-block__info-wrapper">
                                <div class="news-block__info">
                                    <a href="" class="news-block__info-link">{{$cp->title}}</a>
                                    <span class="news-block__date">{{\App\Models\Post::DateTranslate($cp->post_date)}}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function() {
            $("#button_1").click(function(e) {
                e.preventDefault();
                $.ajax({
                    type: "POST",
                    url: "/pages/test/",
                    data: {
                        id: $("#button_1").val(),
                        access_token: $("#access_token").val()
                    },
                    success: function(result) {
                        alert('ok');
                    },
                    error: function(result) {
                        alert('error');
                    }
                });
            });
    </script>
@endsection

resources/views/main/multimedia.blade.php
@extends('main.home_master')
@section('content')
    <br>
    <section class="categories-news">
        <div class="container">


            <div class="row">

                @foreach($multimedia as $cp)
                    <div class="col-sm-3 col-6">
                        <div class="news-block__medium news-block__medium_media news-block__medium_region">
                            <a href=""><img src="{{url($cp->image)}}" alt="" class="news-block__image img-fluid"></a>
                            <div class="news-block__info-wrapper">
                                <div class="news-block__info">
                                    <a href="" class="news-block__info-link">{{$cp->title}}</a>

                                    @if($cp->is_video_content==1)
                                        <span>{{trans('front.video')}}</span>
                                    @elseif($cp->is_photo_content==1)
                                        <span>{{trans('front.photo')}}</span>
                                    @elseif($cp->is_audio_content==1)
                                        <span>{{trans('front.audio')}}</span>
                                    @endif
                                    <span class="news-block__date">{{\App\Models\Post::DateTranslate($cp->post_date)}}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </section>
@endsection

resources/views/main/search.blade.php
@extends('main.home_master')
@section('content')

    <!-- Page Banner Section Start -->

    <!-- Post Section Start -->
    <section class="categories-news">

        <div class="container">
            <div class="row">
                @foreach($posts as $cp)
                    <br>

                    <div class="col-sm-3 col-6">

                        <div class="news-block__medium news-block__medium_media news-block__medium_region">
                            <a href=""><img src="{{url($cp->image)}}" alt="" class="news-block__image img-fluid"></a>
                            <div class="news-block__info-wrapper">
                                <div class="news-block__info">
                                    <a href="" class="news-block__info-link">{{$cp->title}}</a>
                                    <span
                                        class="news-block__date">{{\App\Models\Post::DateTranslate($cp->post_date)}}</span>
                                </div>
                            </div>
                        </div>

                    </div>
                @endforeach
            </div>
        </div>

    </section>
@endsection

resources/views/main/subposts.blade.php
@extends('main.home_master')
@section('content')
    <section class="categories-news">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2 class="categories-news__title">{{$subcat_name->subcategory_name}}</h2>
                </div>

                @foreach($subcatposts as $cp)
                    <div class="col-sm-3 col-6">
                        <div class="news-block__medium news-block__medium_media news-block__medium_region">
                            <a href=""><img src="{{url($cp->image)}}" alt="" class="news-block__image img-fluid"></a>
                            <div class="news-block__info-wrapper">
                                <div class="news-block__info">
                                    <a href="" class="news-block__info-link">{{$cp->title}}</a>
                                    <span class="news-block__date">{{\App\Models\Post::DateTranslate($cp->post_date)}}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </section>
@endsection